CUDA_VISIBLE_DEVICES=3 python3 main_pretrain_CL.py \
    --dataset tinyimagenet \
    --backbone resnet18 \
    --train_data_path /mnt/hdd1/chencheng/cl_dataset/Tinyimagenet/ \
    --val_data_path /mnt/hdd1/chencheng/cl_dataset/Tinyimagenet/ \
    --max_epochs 200 \
    --Task 10 \
    --devices 0 \
    --accelerator gpu \
    --optimizer sgd \
    --scheduler none \
    --lr 0.03 \
    --classifier_lr 0.3 \
    --weight_decay 0.0005 \
    --batch_size 256 \
    --num_workers 4 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.4 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --crop_size 64 \
    --num_crops_per_aug 1 1 \
    --name mocov2plus \
    --project CUCL_855_Tiny \
    --entity zacks \
    --wandb \
    --method mocov2plus \
    --knn_k 100 \
    --knn_temperature 0.1 \
    --knn_distance_function cosine \
    --knn_feature_type backbone \
    --proj_hidden_dim 2048 \
    --proj_output_dim 512 \
    --queue_size 32768 \
    --temperature 0.2 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 0.999 \
    --momentum_classifier \
    # --offline \
    # --save_checkpoint \
    # --auto_resume \
